(TeX-add-style-hook
 "tangent_space_of_curves"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4" "danish")))
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art10"
    "amssymb"
    "amsmath"
    "xcolor"
    "soul"
    "enumerate"
    "verbatim"
    "amsthm"
    "graphicx")
   (TeX-add-symbols
    "Z"
    "Q"
    "R"
    "N"
    "C"
    "I"
    "blank"
    "diff")
   (LaTeX-add-labels
    "sec:manifold-curves"
    "sec:parametrized-curves"
    "sec:defin-metr-tang-2"
    "prop:horizontal-path"
    "eq:canon-repar"
    "remark:ortho-decom"
    "def:tang-quotient"
    "eq:tang-quotient"
    "eq:length-quotient"
    "sec:test-section-2"
    "sec:quest--cons"
    "sec:defin-metr-tang"
    "eq:tang-orbit")
   (LaTeX-add-environments
    "theorem"
    "lemma"
    "proposition"
    "corollary"
    "definition"
    "example"
    "remark"
    "note"))
 :latex)

