(TeX-add-style-hook
 "tangent_space_of_curves"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4" "danish")))
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art10"
    "amssymb"
    "amsmath"
    "xcolor"
    "soul"
    "enumerate"
    "verbatim"
    "amsthm"
    "graphicx"
    "caption"
    "subcaption")
   (TeX-add-symbols
    "Z"
    "Q"
    "R"
    "N"
    "C"
    "I"
    "blank"
    "diff")
   (LaTeX-add-labels
    "sec:manifold-curves"
    "fig:circle-mapping"
    "sec:parametrized-curves"
    "eq:path-in-imm"
    "fig:def-tang-imm"
    "def:length-in-imm"
    "sec:manif-unpar-curv"
    "prop:horizontal-path"
    "eq:canon-repar"
    "remark:ortho-decom"
    "def:tang-quotient"
    "eq:tang-quotient"
    "eq:length-quotient"
    "sec:hlcomp-this-form"
    "sec:l2-metric-vanishes"
    "sec:quest--cons"
    "sec:defin-metr-tang"
    "eq:tang-orbit"
    "sec:short-constr-tang")
   (LaTeX-add-amsthm-newtheorems
    "theorem"
    "lemma"
    "proposition"
    "corollary"
    "definition"
    "example"
    "remark"
    "note")
   (LaTeX-add-amsthm-newtheoremstyles
    "break"
    "Break"))
 :latex)

